apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress-qa
  namespace: qa  # QA namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: my-springboot.local
    http:
      paths:
      - path: /qa
        pathType: Prefix
        backend:
          service:
            name: springboot-service
            port:
              number: 7000  # Forward requests to service on port 7000
