apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: springboot-ingress-dev
  namespace: default  # Dev namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: my-springboot.local
      http:
        paths:
          - path: /dev
            pathType: Prefix
            backend:
              service:
                name: springboot-service
                port:
                  number: 7000
